spring:
  application: bugtracker
  version: @project.version@
  messages:
    encoding: UTF-8
    basename: i18n/messages
  tomcat:
    uri-encoding: UTF-8

  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: ${DB_URL:jdbc:mysql://localhost:3306/bugtracker?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
      username: ${DB_USER:root}
      password: ${DB_USER:root}
      hikari:
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  jpa:
        generate-ddl: true
        open-in-view: true
        hibernate:
          ddl-auto: create-drop
          physical-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          implicit-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
  sql:
    init:
      data-locations: classpath*:import.sql
      continue-on-error: true
app:
  jwt:
    secret: F$gQb+D$wjV&EsV}(;!^{|[GM^9Y6'33n'FG^-!tF&?Z[P{Wl{~m*`wp7XSd>Fa
    expirationms: 604800000
server:
  port: 2000
  error:
    include-message: always
    include-binding-errors: always